# ===================================
#  List Behavior Config
# ===================================

title: Access Log
list: @/modules/backend/models/accesslog/columns.yaml
modelClass: Backend\Models\AccessLog
recordUrl: backend/accesslogs/preview/:id
noRecordsMessage: backend::lang.list.no_records
showSetup: false

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt